# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'form.ui'
##
## Created by: Qt User Interface Compiler version 6.9.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QGraphicsView,
    QGroupBox, QLabel, QLineEdit, QMainWindow,
    QPushButton, QSizePolicy, QStatusBar, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1188, 775)
        MainWindow.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.group_box2 = QGroupBox(self.centralwidget)
        self.group_box2.setObjectName(u"group_box2")
        self.group_box2.setGeometry(QRect(10, 460, 1171, 261))
        font = QFont()
        font.setPointSize(13)
        self.group_box2.setFont(font)
        self.group_box2.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.bicycle_chkbox = QCheckBox(self.group_box2)
        self.bicycle_chkbox.setObjectName(u"bicycle_chkbox")
        self.bicycle_chkbox.setGeometry(QRect(100, 30, 85, 20))
        self.car_chkbox = QCheckBox(self.group_box2)
        self.car_chkbox.setObjectName(u"car_chkbox")
        self.car_chkbox.setGeometry(QRect(210, 30, 85, 20))
        self.motorbike_chkbox = QCheckBox(self.group_box2)
        self.motorbike_chkbox.setObjectName(u"motorbike_chkbox")
        self.motorbike_chkbox.setGeometry(QRect(310, 30, 101, 20))
        self.aeroplane_chkbox = QCheckBox(self.group_box2)
        self.aeroplane_chkbox.setObjectName(u"aeroplane_chkbox")
        self.aeroplane_chkbox.setGeometry(QRect(410, 30, 111, 20))
        self.bus_chkbox = QCheckBox(self.group_box2)
        self.bus_chkbox.setObjectName(u"bus_chkbox")
        self.bus_chkbox.setGeometry(QRect(540, 30, 85, 20))
        self.train_chkbox = QCheckBox(self.group_box2)
        self.train_chkbox.setObjectName(u"train_chkbox")
        self.train_chkbox.setGeometry(QRect(640, 30, 85, 20))
        self.person_chkbox = QCheckBox(self.group_box2)
        self.person_chkbox.setObjectName(u"person_chkbox")
        self.person_chkbox.setGeometry(QRect(0, 30, 85, 20))
        self.truck_chkbox = QCheckBox(self.group_box2)
        self.truck_chkbox.setObjectName(u"truck_chkbox")
        self.truck_chkbox.setGeometry(QRect(740, 30, 85, 20))
        self.boat_chkbox = QCheckBox(self.group_box2)
        self.boat_chkbox.setObjectName(u"boat_chkbox")
        self.boat_chkbox.setGeometry(QRect(0, 60, 85, 20))
        self.traffic_light_chkbox = QCheckBox(self.group_box2)
        self.traffic_light_chkbox.setObjectName(u"traffic_light_chkbox")
        self.traffic_light_chkbox.setGeometry(QRect(100, 60, 85, 20))
        self.fire_hydrant_chkbox = QCheckBox(self.group_box2)
        self.fire_hydrant_chkbox.setObjectName(u"fire_hydrant_chkbox")
        self.fire_hydrant_chkbox.setGeometry(QRect(210, 60, 91, 20))
        self.stop_sign_chkbox = QCheckBox(self.group_box2)
        self.stop_sign_chkbox.setObjectName(u"stop_sign_chkbox")
        self.stop_sign_chkbox.setGeometry(QRect(310, 60, 101, 20))
        self.parking_meter_chkbox = QCheckBox(self.group_box2)
        self.parking_meter_chkbox.setObjectName(u"parking_meter_chkbox")
        self.parking_meter_chkbox.setGeometry(QRect(410, 60, 121, 20))
        self.bench_chkbox = QCheckBox(self.group_box2)
        self.bench_chkbox.setObjectName(u"bench_chkbox")
        self.bench_chkbox.setGeometry(QRect(540, 60, 85, 20))
        self.bird_chkbox = QCheckBox(self.group_box2)
        self.bird_chkbox.setObjectName(u"bird_chkbox")
        self.bird_chkbox.setGeometry(QRect(640, 60, 85, 20))
        self.cat_chkbox = QCheckBox(self.group_box2)
        self.cat_chkbox.setObjectName(u"cat_chkbox")
        self.cat_chkbox.setGeometry(QRect(850, 30, 85, 20))
        self.dog_chkbox = QCheckBox(self.group_box2)
        self.dog_chkbox.setObjectName(u"dog_chkbox")
        self.dog_chkbox.setGeometry(QRect(0, 90, 81, 20))
        self.horse_chkbox = QCheckBox(self.group_box2)
        self.horse_chkbox.setObjectName(u"horse_chkbox")
        self.horse_chkbox.setGeometry(QRect(100, 90, 85, 20))
        self.sheep_chkbox = QCheckBox(self.group_box2)
        self.sheep_chkbox.setObjectName(u"sheep_chkbox")
        self.sheep_chkbox.setGeometry(QRect(210, 90, 85, 20))
        self.cow_chkbox = QCheckBox(self.group_box2)
        self.cow_chkbox.setObjectName(u"cow_chkbox")
        self.cow_chkbox.setGeometry(QRect(310, 90, 85, 20))
        self.elephant_chkbox = QCheckBox(self.group_box2)
        self.elephant_chkbox.setObjectName(u"elephant_chkbox")
        self.elephant_chkbox.setGeometry(QRect(410, 90, 121, 20))
        self.bear_chkbox = QCheckBox(self.group_box2)
        self.bear_chkbox.setObjectName(u"bear_chkbox")
        self.bear_chkbox.setGeometry(QRect(540, 90, 85, 20))
        self.zebra_chkbox = QCheckBox(self.group_box2)
        self.zebra_chkbox.setObjectName(u"zebra_chkbox")
        self.zebra_chkbox.setGeometry(QRect(640, 90, 85, 20))
        self.giraffe_chkbox = QCheckBox(self.group_box2)
        self.giraffe_chkbox.setObjectName(u"giraffe_chkbox")
        self.giraffe_chkbox.setGeometry(QRect(850, 60, 85, 20))
        self.backpack_chkbox = QCheckBox(self.group_box2)
        self.backpack_chkbox.setObjectName(u"backpack_chkbox")
        self.backpack_chkbox.setGeometry(QRect(0, 120, 85, 20))
        self.umbrella_chkbox = QCheckBox(self.group_box2)
        self.umbrella_chkbox.setObjectName(u"umbrella_chkbox")
        self.umbrella_chkbox.setGeometry(QRect(100, 120, 85, 20))
        self.handbag_chkbox = QCheckBox(self.group_box2)
        self.handbag_chkbox.setObjectName(u"handbag_chkbox")
        self.handbag_chkbox.setGeometry(QRect(210, 120, 85, 20))
        self.tie_chkbox = QCheckBox(self.group_box2)
        self.tie_chkbox.setObjectName(u"tie_chkbox")
        self.tie_chkbox.setGeometry(QRect(310, 120, 85, 20))
        self.suitcase_chkbox = QCheckBox(self.group_box2)
        self.suitcase_chkbox.setObjectName(u"suitcase_chkbox")
        self.suitcase_chkbox.setGeometry(QRect(410, 120, 85, 20))
        self.frisbee_chkbox = QCheckBox(self.group_box2)
        self.frisbee_chkbox.setObjectName(u"frisbee_chkbox")
        self.frisbee_chkbox.setGeometry(QRect(540, 120, 85, 20))
        self.skis_chkbox = QCheckBox(self.group_box2)
        self.skis_chkbox.setObjectName(u"skis_chkbox")
        self.skis_chkbox.setGeometry(QRect(640, 120, 85, 20))
        self.snowboard_chkbox = QCheckBox(self.group_box2)
        self.snowboard_chkbox.setObjectName(u"snowboard_chkbox")
        self.snowboard_chkbox.setGeometry(QRect(740, 60, 91, 20))
        self.kite_chkbox = QCheckBox(self.group_box2)
        self.kite_chkbox.setObjectName(u"kite_chkbox")
        self.kite_chkbox.setGeometry(QRect(0, 150, 85, 20))
        self.baseball_bat_chkbox = QCheckBox(self.group_box2)
        self.baseball_bat_chkbox.setObjectName(u"baseball_bat_chkbox")
        self.baseball_bat_chkbox.setGeometry(QRect(100, 150, 101, 20))
        self.baseball_glove_chkbox = QCheckBox(self.group_box2)
        self.baseball_glove_chkbox.setObjectName(u"baseball_glove_chkbox")
        self.baseball_glove_chkbox.setGeometry(QRect(410, 150, 111, 20))
        self.skateboard_chkbox = QCheckBox(self.group_box2)
        self.skateboard_chkbox.setObjectName(u"skateboard_chkbox")
        self.skateboard_chkbox.setGeometry(QRect(210, 150, 101, 20))
        self.bottle_chkbox = QCheckBox(self.group_box2)
        self.bottle_chkbox.setObjectName(u"bottle_chkbox")
        self.bottle_chkbox.setGeometry(QRect(540, 150, 85, 20))
        self.wine_glass_chkbox = QCheckBox(self.group_box2)
        self.wine_glass_chkbox.setObjectName(u"wine_glass_chkbox")
        self.wine_glass_chkbox.setGeometry(QRect(640, 150, 85, 20))
        self.cup_chkbox = QCheckBox(self.group_box2)
        self.cup_chkbox.setObjectName(u"cup_chkbox")
        self.cup_chkbox.setGeometry(QRect(740, 90, 85, 20))
        self.fork_chkbox = QCheckBox(self.group_box2)
        self.fork_chkbox.setObjectName(u"fork_chkbox")
        self.fork_chkbox.setGeometry(QRect(0, 180, 85, 20))
        self.knife_chkbox = QCheckBox(self.group_box2)
        self.knife_chkbox.setObjectName(u"knife_chkbox")
        self.knife_chkbox.setGeometry(QRect(100, 180, 85, 20))
        self.spoon_chkbox = QCheckBox(self.group_box2)
        self.spoon_chkbox.setObjectName(u"spoon_chkbox")
        self.spoon_chkbox.setGeometry(QRect(210, 180, 85, 20))
        self.bowl_chkbox = QCheckBox(self.group_box2)
        self.bowl_chkbox.setObjectName(u"bowl_chkbox")
        self.bowl_chkbox.setGeometry(QRect(310, 180, 85, 20))
        self.tennis_racket_chkbox = QCheckBox(self.group_box2)
        self.tennis_racket_chkbox.setObjectName(u"tennis_racket_chkbox")
        self.tennis_racket_chkbox.setGeometry(QRect(410, 180, 111, 20))
        self.banana_chkbox = QCheckBox(self.group_box2)
        self.banana_chkbox.setObjectName(u"banana_chkbox")
        self.banana_chkbox.setGeometry(QRect(540, 180, 85, 20))
        self.apple_chkbox = QCheckBox(self.group_box2)
        self.apple_chkbox.setObjectName(u"apple_chkbox")
        self.apple_chkbox.setGeometry(QRect(640, 180, 85, 20))
        self.sandwich_chkbox = QCheckBox(self.group_box2)
        self.sandwich_chkbox.setObjectName(u"sandwich_chkbox")
        self.sandwich_chkbox.setGeometry(QRect(850, 90, 85, 20))
        self.surfboard_chkbox = QCheckBox(self.group_box2)
        self.surfboard_chkbox.setObjectName(u"surfboard_chkbox")
        self.surfboard_chkbox.setGeometry(QRect(310, 150, 85, 20))
        self.orange_chkbox = QCheckBox(self.group_box2)
        self.orange_chkbox.setObjectName(u"orange_chkbox")
        self.orange_chkbox.setGeometry(QRect(0, 210, 85, 20))
        self.broccoli_chkbox = QCheckBox(self.group_box2)
        self.broccoli_chkbox.setObjectName(u"broccoli_chkbox")
        self.broccoli_chkbox.setGeometry(QRect(100, 210, 85, 20))
        self.carrot_chkbox = QCheckBox(self.group_box2)
        self.carrot_chkbox.setObjectName(u"carrot_chkbox")
        self.carrot_chkbox.setGeometry(QRect(210, 210, 85, 20))
        self.hot_dog_chkbox = QCheckBox(self.group_box2)
        self.hot_dog_chkbox.setObjectName(u"hot_dog_chkbox")
        self.hot_dog_chkbox.setGeometry(QRect(310, 210, 85, 20))
        self.pizza_chkbox = QCheckBox(self.group_box2)
        self.pizza_chkbox.setObjectName(u"pizza_chkbox")
        self.pizza_chkbox.setGeometry(QRect(410, 210, 85, 20))
        self.donut_chkbox = QCheckBox(self.group_box2)
        self.donut_chkbox.setObjectName(u"donut_chkbox")
        self.donut_chkbox.setGeometry(QRect(540, 210, 85, 20))
        self.cake_chkbox = QCheckBox(self.group_box2)
        self.cake_chkbox.setObjectName(u"cake_chkbox")
        self.cake_chkbox.setGeometry(QRect(640, 210, 85, 20))
        self.chair_chkbox = QCheckBox(self.group_box2)
        self.chair_chkbox.setObjectName(u"chair_chkbox")
        self.chair_chkbox.setGeometry(QRect(740, 120, 85, 20))
        self.sofa_chkbox = QCheckBox(self.group_box2)
        self.sofa_chkbox.setObjectName(u"sofa_chkbox")
        self.sofa_chkbox.setGeometry(QRect(0, 240, 85, 20))
        self.pottedplant_chkbox = QCheckBox(self.group_box2)
        self.pottedplant_chkbox.setObjectName(u"pottedplant_chkbox")
        self.pottedplant_chkbox.setGeometry(QRect(100, 240, 85, 20))
        self.bed_chkbox = QCheckBox(self.group_box2)
        self.bed_chkbox.setObjectName(u"bed_chkbox")
        self.bed_chkbox.setGeometry(QRect(210, 240, 85, 20))
        self.diningtable_chkbox = QCheckBox(self.group_box2)
        self.diningtable_chkbox.setObjectName(u"diningtable_chkbox")
        self.diningtable_chkbox.setGeometry(QRect(950, 90, 91, 20))
        self.toilet_chkbox = QCheckBox(self.group_box2)
        self.toilet_chkbox.setObjectName(u"toilet_chkbox")
        self.toilet_chkbox.setGeometry(QRect(950, 60, 85, 20))
        self.tvmonitor_chkbox = QCheckBox(self.group_box2)
        self.tvmonitor_chkbox.setObjectName(u"tvmonitor_chkbox")
        self.tvmonitor_chkbox.setGeometry(QRect(950, 30, 85, 20))
        self.laptop_chkbox = QCheckBox(self.group_box2)
        self.laptop_chkbox.setObjectName(u"laptop_chkbox")
        self.laptop_chkbox.setGeometry(QRect(1060, 210, 85, 20))
        self.mouse_chkbox = QCheckBox(self.group_box2)
        self.mouse_chkbox.setObjectName(u"mouse_chkbox")
        self.mouse_chkbox.setGeometry(QRect(850, 120, 85, 20))
        self.remote_chkbox = QCheckBox(self.group_box2)
        self.remote_chkbox.setObjectName(u"remote_chkbox")
        self.remote_chkbox.setGeometry(QRect(1060, 90, 85, 20))
        self.keyboard_chkbox = QCheckBox(self.group_box2)
        self.keyboard_chkbox.setObjectName(u"keyboard_chkbox")
        self.keyboard_chkbox.setGeometry(QRect(1060, 60, 85, 20))
        self.cell_phone_chkbox = QCheckBox(self.group_box2)
        self.cell_phone_chkbox.setObjectName(u"cell_phone_chkbox")
        self.cell_phone_chkbox.setGeometry(QRect(1060, 30, 85, 20))
        self.microwave_chkbox = QCheckBox(self.group_box2)
        self.microwave_chkbox.setObjectName(u"microwave_chkbox")
        self.microwave_chkbox.setGeometry(QRect(1060, 120, 85, 20))
        self.oven_chkbox = QCheckBox(self.group_box2)
        self.oven_chkbox.setObjectName(u"oven_chkbox")
        self.oven_chkbox.setGeometry(QRect(950, 210, 85, 20))
        self.toaster_chkbox = QCheckBox(self.group_box2)
        self.toaster_chkbox.setObjectName(u"toaster_chkbox")
        self.toaster_chkbox.setGeometry(QRect(950, 180, 85, 20))
        self.sink_chkbox = QCheckBox(self.group_box2)
        self.sink_chkbox.setObjectName(u"sink_chkbox")
        self.sink_chkbox.setGeometry(QRect(950, 150, 85, 20))
        self.refrigerator_chkbox = QCheckBox(self.group_box2)
        self.refrigerator_chkbox.setObjectName(u"refrigerator_chkbox")
        self.refrigerator_chkbox.setGeometry(QRect(740, 150, 91, 20))
        self.book_chkbox = QCheckBox(self.group_box2)
        self.book_chkbox.setObjectName(u"book_chkbox")
        self.book_chkbox.setGeometry(QRect(1060, 150, 85, 20))
        self.clock_chkbox = QCheckBox(self.group_box2)
        self.clock_chkbox.setObjectName(u"clock_chkbox")
        self.clock_chkbox.setGeometry(QRect(1060, 180, 85, 20))
        self.vase_chkbox = QCheckBox(self.group_box2)
        self.vase_chkbox.setObjectName(u"vase_chkbox")
        self.vase_chkbox.setGeometry(QRect(850, 210, 85, 20))
        self.scissors_chkbox = QCheckBox(self.group_box2)
        self.scissors_chkbox.setObjectName(u"scissors_chkbox")
        self.scissors_chkbox.setGeometry(QRect(740, 210, 85, 20))
        self.teddy_bear_chkbox = QCheckBox(self.group_box2)
        self.teddy_bear_chkbox.setObjectName(u"teddy_bear_chkbox")
        self.teddy_bear_chkbox.setGeometry(QRect(850, 180, 85, 20))
        self.hair_drier_chkbox = QCheckBox(self.group_box2)
        self.hair_drier_chkbox.setObjectName(u"hair_drier_chkbox")
        self.hair_drier_chkbox.setGeometry(QRect(740, 180, 85, 20))
        self.toothbrush_chkbox = QCheckBox(self.group_box2)
        self.toothbrush_chkbox.setObjectName(u"toothbrush_chkbox")
        self.toothbrush_chkbox.setGeometry(QRect(850, 150, 91, 20))
        self.sports_ball_chkbox = QCheckBox(self.group_box2)
        self.sports_ball_chkbox.setObjectName(u"sports_ball_chkbox")
        self.sports_ball_chkbox.setGeometry(QRect(950, 120, 85, 20))
        self.group_box1 = QGroupBox(self.centralwidget)
        self.group_box1.setObjectName(u"group_box1")
        self.group_box1.setGeometry(QRect(10, 370, 1171, 91))
        self.group_box1.setFont(font)
        self.group_box1.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label = QLabel(self.group_box1)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 30, 41, 21))
        self.host_input = QLineEdit(self.group_box1)
        self.host_input.setObjectName(u"host_input")
        self.host_input.setGeometry(QRect(90, 30, 121, 21))
        self.label_6 = QLabel(self.group_box1)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(800, 30, 58, 21))
        self.protocol_cbb = QComboBox(self.group_box1)
        self.protocol_cbb.addItem("")
        self.protocol_cbb.setObjectName(u"protocol_cbb")
        self.protocol_cbb.setGeometry(QRect(860, 30, 141, 21))
        self.label_2 = QLabel(self.group_box1)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(240, 30, 41, 21))
        self.port_input = QLineEdit(self.group_box1)
        self.port_input.setObjectName(u"port_input")
        self.port_input.setGeometry(QRect(280, 30, 131, 21))
        self.stream_path_input = QLineEdit(self.group_box1)
        self.stream_path_input.setObjectName(u"stream_path_input")
        self.stream_path_input.setGeometry(QRect(90, 60, 131, 21))
        self.label_5 = QLabel(self.group_box1)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 60, 81, 21))
        self.label_3 = QLabel(self.group_box1)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(430, 30, 41, 21))
        self.user_input = QLineEdit(self.group_box1)
        self.user_input.setObjectName(u"user_input")
        self.user_input.setGeometry(QRect(480, 30, 121, 21))
        self.label_4 = QLabel(self.group_box1)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(620, 30, 41, 21))
        self.pass_input = QLineEdit(self.group_box1)
        self.pass_input.setObjectName(u"pass_input")
        self.pass_input.setGeometry(QRect(660, 30, 121, 21))
        self.pass_input.setInputMethodHints(Qt.InputMethodHint.ImhNone)
        self.label_7 = QLabel(self.group_box1)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(240, 60, 51, 21))
        self.api_input = QLineEdit(self.group_box1)
        self.api_input.setObjectName(u"api_input")
        self.api_input.setGeometry(QRect(280, 60, 121, 21))
        self.token_input = QLineEdit(self.group_box1)
        self.token_input.setObjectName(u"token_input")
        self.token_input.setGeometry(QRect(480, 60, 121, 21))
        self.label_9 = QLabel(self.group_box1)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(430, 60, 58, 21))
        self.label_10 = QLabel(self.group_box1)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(620, 60, 58, 21))
        self.etd_input = QLineEdit(self.group_box1)
        self.etd_input.setObjectName(u"etd_input")
        self.etd_input.setGeometry(QRect(660, 60, 121, 21))
        self.label_11 = QLabel(self.group_box1)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(1010, 30, 31, 21))
        self.ai_cbb = QComboBox(self.group_box1)
        self.ai_cbb.addItem("")
        self.ai_cbb.addItem("")
        self.ai_cbb.addItem("")
        self.ai_cbb.addItem("")
        self.ai_cbb.addItem("")
        self.ai_cbb.addItem("")
        self.ai_cbb.addItem("")
        self.ai_cbb.addItem("")
        self.ai_cbb.addItem("")
        self.ai_cbb.addItem("")
        self.ai_cbb.addItem("")
        self.ai_cbb.addItem("")
        self.ai_cbb.addItem("")
        self.ai_cbb.addItem("")
        self.ai_cbb.addItem("")
        self.ai_cbb.addItem("")
        self.ai_cbb.addItem("")
        self.ai_cbb.addItem("")
        self.ai_cbb.addItem("")
        self.ai_cbb.addItem("")
        self.ai_cbb.addItem("")
        self.ai_cbb.addItem("")
        self.ai_cbb.addItem("")
        self.ai_cbb.addItem("")
        self.ai_cbb.addItem("")
        self.ai_cbb.setObjectName(u"ai_cbb")
        self.ai_cbb.setGeometry(QRect(1030, 20, 141, 41))
        self.graphics_view = QGraphicsView(self.centralwidget)
        self.graphics_view.setObjectName(u"graphics_view")
        self.graphics_view.setGeometry(QRect(10, 10, 1171, 361))
        self.graphics_view.setAutoFillBackground(True)
        self.start_btn = QPushButton(self.centralwidget)
        self.start_btn.setObjectName(u"start_btn")
        self.start_btn.setGeometry(QRect(570, 720, 131, 32))
        self.stop_btn = QPushButton(self.centralwidget)
        self.stop_btn.setObjectName(u"stop_btn")
        self.stop_btn.setEnabled(False)
        self.stop_btn.setGeometry(QRect(420, 720, 131, 32))
        self.read_label = QLabel(self.centralwidget)
        self.read_label.setObjectName(u"read_label")
        self.read_label.setGeometry(QRect(1060, 720, 111, 31))
        self.yolo_label = QLabel(self.centralwidget)
        self.yolo_label.setObjectName(u"yolo_label")
        self.yolo_label.setGeometry(QRect(940, 720, 111, 31))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"RTSP Stream Viewer", None))
        self.group_box2.setTitle(QCoreApplication.translate("MainWindow", u"Detection Object:", None))
        self.bicycle_chkbox.setText(QCoreApplication.translate("MainWindow", u"bicycle", None))
        self.car_chkbox.setText(QCoreApplication.translate("MainWindow", u"car", None))
        self.motorbike_chkbox.setText(QCoreApplication.translate("MainWindow", u"motorbike", None))
        self.aeroplane_chkbox.setText(QCoreApplication.translate("MainWindow", u"aeroplane", None))
        self.bus_chkbox.setText(QCoreApplication.translate("MainWindow", u"bus", None))
        self.train_chkbox.setText(QCoreApplication.translate("MainWindow", u"train", None))
        self.person_chkbox.setText(QCoreApplication.translate("MainWindow", u"person", None))
        self.truck_chkbox.setText(QCoreApplication.translate("MainWindow", u"truck", None))
        self.boat_chkbox.setText(QCoreApplication.translate("MainWindow", u"boat", None))
        self.traffic_light_chkbox.setText(QCoreApplication.translate("MainWindow", u"traffic light", None))
        self.fire_hydrant_chkbox.setText(QCoreApplication.translate("MainWindow", u"fire hydrant", None))
        self.stop_sign_chkbox.setText(QCoreApplication.translate("MainWindow", u"stop sign", None))
        self.parking_meter_chkbox.setText(QCoreApplication.translate("MainWindow", u"parking meter", None))
        self.bench_chkbox.setText(QCoreApplication.translate("MainWindow", u"bench", None))
        self.bird_chkbox.setText(QCoreApplication.translate("MainWindow", u"bird", None))
        self.cat_chkbox.setText(QCoreApplication.translate("MainWindow", u"cat", None))
        self.dog_chkbox.setText(QCoreApplication.translate("MainWindow", u"dog", None))
        self.horse_chkbox.setText(QCoreApplication.translate("MainWindow", u"horse", None))
        self.sheep_chkbox.setText(QCoreApplication.translate("MainWindow", u"sheep", None))
        self.cow_chkbox.setText(QCoreApplication.translate("MainWindow", u"cow", None))
        self.elephant_chkbox.setText(QCoreApplication.translate("MainWindow", u"elephant", None))
        self.bear_chkbox.setText(QCoreApplication.translate("MainWindow", u"bear", None))
        self.zebra_chkbox.setText(QCoreApplication.translate("MainWindow", u"zebra", None))
        self.giraffe_chkbox.setText(QCoreApplication.translate("MainWindow", u"giraffe", None))
        self.backpack_chkbox.setText(QCoreApplication.translate("MainWindow", u"backpack", None))
        self.umbrella_chkbox.setText(QCoreApplication.translate("MainWindow", u"umbrella", None))
        self.handbag_chkbox.setText(QCoreApplication.translate("MainWindow", u"handbag", None))
        self.tie_chkbox.setText(QCoreApplication.translate("MainWindow", u"tie", None))
        self.suitcase_chkbox.setText(QCoreApplication.translate("MainWindow", u"suitcase", None))
        self.frisbee_chkbox.setText(QCoreApplication.translate("MainWindow", u"frisbee", None))
        self.skis_chkbox.setText(QCoreApplication.translate("MainWindow", u"skis", None))
        self.snowboard_chkbox.setText(QCoreApplication.translate("MainWindow", u"snowboard", None))
        self.kite_chkbox.setText(QCoreApplication.translate("MainWindow", u"kite", None))
        self.baseball_bat_chkbox.setText(QCoreApplication.translate("MainWindow", u"baseball bat", None))
        self.baseball_glove_chkbox.setText(QCoreApplication.translate("MainWindow", u"baseball glove", None))
        self.skateboard_chkbox.setText(QCoreApplication.translate("MainWindow", u"skateboard", None))
        self.bottle_chkbox.setText(QCoreApplication.translate("MainWindow", u"bottle", None))
        self.wine_glass_chkbox.setText(QCoreApplication.translate("MainWindow", u"wine glass", None))
        self.cup_chkbox.setText(QCoreApplication.translate("MainWindow", u"cup", None))
        self.fork_chkbox.setText(QCoreApplication.translate("MainWindow", u"fork", None))
        self.knife_chkbox.setText(QCoreApplication.translate("MainWindow", u"knife", None))
        self.spoon_chkbox.setText(QCoreApplication.translate("MainWindow", u"spoon", None))
        self.bowl_chkbox.setText(QCoreApplication.translate("MainWindow", u"bowl", None))
        self.tennis_racket_chkbox.setText(QCoreApplication.translate("MainWindow", u"tennis racket", None))
        self.banana_chkbox.setText(QCoreApplication.translate("MainWindow", u"banana", None))
        self.apple_chkbox.setText(QCoreApplication.translate("MainWindow", u"apple", None))
        self.sandwich_chkbox.setText(QCoreApplication.translate("MainWindow", u"sandwich", None))
        self.surfboard_chkbox.setText(QCoreApplication.translate("MainWindow", u"surfboard", None))
        self.orange_chkbox.setText(QCoreApplication.translate("MainWindow", u"orange", None))
        self.broccoli_chkbox.setText(QCoreApplication.translate("MainWindow", u"broccoli", None))
        self.carrot_chkbox.setText(QCoreApplication.translate("MainWindow", u"carrot", None))
        self.hot_dog_chkbox.setText(QCoreApplication.translate("MainWindow", u"hot dog", None))
        self.pizza_chkbox.setText(QCoreApplication.translate("MainWindow", u"pizza", None))
        self.donut_chkbox.setText(QCoreApplication.translate("MainWindow", u"donut", None))
        self.cake_chkbox.setText(QCoreApplication.translate("MainWindow", u"cake", None))
        self.chair_chkbox.setText(QCoreApplication.translate("MainWindow", u"chair", None))
        self.sofa_chkbox.setText(QCoreApplication.translate("MainWindow", u"sofa", None))
        self.pottedplant_chkbox.setText(QCoreApplication.translate("MainWindow", u"pottedplant", None))
        self.bed_chkbox.setText(QCoreApplication.translate("MainWindow", u"bed", None))
        self.diningtable_chkbox.setText(QCoreApplication.translate("MainWindow", u"diningtable", None))
        self.toilet_chkbox.setText(QCoreApplication.translate("MainWindow", u"toilet", None))
        self.tvmonitor_chkbox.setText(QCoreApplication.translate("MainWindow", u"tvmonitor", None))
        self.laptop_chkbox.setText(QCoreApplication.translate("MainWindow", u"laptop", None))
        self.mouse_chkbox.setText(QCoreApplication.translate("MainWindow", u"mouse", None))
        self.remote_chkbox.setText(QCoreApplication.translate("MainWindow", u"remote", None))
        self.keyboard_chkbox.setText(QCoreApplication.translate("MainWindow", u"keyboard", None))
        self.cell_phone_chkbox.setText(QCoreApplication.translate("MainWindow", u"cell phone", None))
        self.microwave_chkbox.setText(QCoreApplication.translate("MainWindow", u"microwave", None))
        self.oven_chkbox.setText(QCoreApplication.translate("MainWindow", u"oven", None))
        self.toaster_chkbox.setText(QCoreApplication.translate("MainWindow", u"toaster", None))
        self.sink_chkbox.setText(QCoreApplication.translate("MainWindow", u"sink", None))
        self.refrigerator_chkbox.setText(QCoreApplication.translate("MainWindow", u"refrigerator", None))
        self.book_chkbox.setText(QCoreApplication.translate("MainWindow", u"book", None))
        self.clock_chkbox.setText(QCoreApplication.translate("MainWindow", u"clock", None))
        self.vase_chkbox.setText(QCoreApplication.translate("MainWindow", u"vase", None))
        self.scissors_chkbox.setText(QCoreApplication.translate("MainWindow", u"scissors", None))
        self.teddy_bear_chkbox.setText(QCoreApplication.translate("MainWindow", u"teddy bear", None))
        self.hair_drier_chkbox.setText(QCoreApplication.translate("MainWindow", u"hair drier", None))
        self.toothbrush_chkbox.setText(QCoreApplication.translate("MainWindow", u"toothbrush", None))
        self.sports_ball_chkbox.setText(QCoreApplication.translate("MainWindow", u"sports ball", None))
        self.group_box1.setTitle(QCoreApplication.translate("MainWindow", u"Information", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Host:", None))
        self.host_input.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Please enter ip or domain", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Protocol:", None))
        self.protocol_cbb.setItemText(0, QCoreApplication.translate("MainWindow", u"rtsp://", None))

        self.protocol_cbb.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Please enter protocol", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Port:", None))
        self.port_input.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Please enter port", None))
        self.stream_path_input.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Please enter stream path", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Stream Path:", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"User:", None))
        self.user_input.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Please enter user", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Pass:", None))
        self.pass_input.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Please enter pass", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Api:", None))
        self.api_input.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Please enter api", None))
        self.token_input.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Please enter token", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Token:", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Etd:", None))
        self.etd_input.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Please enter etd", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"AI:", None))
        self.ai_cbb.setItemText(0, QCoreApplication.translate("MainWindow", u"yolov7-tiny", None))
        self.ai_cbb.setItemText(1, QCoreApplication.translate("MainWindow", u"yolov7-lite-e", None))
        self.ai_cbb.setItemText(2, QCoreApplication.translate("MainWindow", u"yolov7-lite-s", None))
        self.ai_cbb.setItemText(3, QCoreApplication.translate("MainWindow", u"yolov7-lite-x", None))
        self.ai_cbb.setItemText(4, QCoreApplication.translate("MainWindow", u"yolov7", None))
        self.ai_cbb.setItemText(5, QCoreApplication.translate("MainWindow", u"yolov7-w6", None))
        self.ai_cbb.setItemText(6, QCoreApplication.translate("MainWindow", u"yolov7-e6", None))
        self.ai_cbb.setItemText(7, QCoreApplication.translate("MainWindow", u"yolov7-d6", None))
        self.ai_cbb.setItemText(8, QCoreApplication.translate("MainWindow", u"yolov7-e6e", None))
        self.ai_cbb.setItemText(9, QCoreApplication.translate("MainWindow", u"yolov7-x", None))
        self.ai_cbb.setItemText(10, QCoreApplication.translate("MainWindow", u"yolov8n.pt", None))
        self.ai_cbb.setItemText(11, QCoreApplication.translate("MainWindow", u"yolov8s.pt", None))
        self.ai_cbb.setItemText(12, QCoreApplication.translate("MainWindow", u"yolov8m.pt", None))
        self.ai_cbb.setItemText(13, QCoreApplication.translate("MainWindow", u"yolov8l.pt", None))
        self.ai_cbb.setItemText(14, QCoreApplication.translate("MainWindow", u"yolov8x.pt", None))
        self.ai_cbb.setItemText(15, QCoreApplication.translate("MainWindow", u"yolov8n-seg.pt", None))
        self.ai_cbb.setItemText(16, QCoreApplication.translate("MainWindow", u"yolov8s-seg.pt", None))
        self.ai_cbb.setItemText(17, QCoreApplication.translate("MainWindow", u"yolov8m-seg.pt", None))
        self.ai_cbb.setItemText(18, QCoreApplication.translate("MainWindow", u"yolov8l-seg.pt", None))
        self.ai_cbb.setItemText(19, QCoreApplication.translate("MainWindow", u"yolov8x-seg.pt", None))
        self.ai_cbb.setItemText(20, QCoreApplication.translate("MainWindow", u"yolov8n-obb", None))
        self.ai_cbb.setItemText(21, QCoreApplication.translate("MainWindow", u"yolov8s-obb", None))
        self.ai_cbb.setItemText(22, QCoreApplication.translate("MainWindow", u"yolov8m-obb", None))
        self.ai_cbb.setItemText(23, QCoreApplication.translate("MainWindow", u"yolov8l-obb", None))
        self.ai_cbb.setItemText(24, QCoreApplication.translate("MainWindow", u"yolov8x-obb", None))

        self.start_btn.setText(QCoreApplication.translate("MainWindow", u"Start", None))
        self.stop_btn.setText(QCoreApplication.translate("MainWindow", u"Stop", None))
        self.read_label.setText(QCoreApplication.translate("MainWindow", u"Read:", None))
        self.yolo_label.setText(QCoreApplication.translate("MainWindow", u"Yolo:", None))
    # retranslateUi

